name: Build and Publish NuGet Package

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the project
        run: dotnet build --configuration Release --no-restore

      - name: Pack the project
        run: dotnet pack --configuration Release --no-build --output ./nupkg

      - name: Verify NuGet API Key
        run: |
          if (-Not [string]::IsNullOrEmpty($env:NUGET_API_KEY)) {
              Write-Host "NuGet API Key is set."
          } else {
            Write-Host "NuGet API Key is not set."
            exit 1
          }
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

      - name: Publish NuGet Package
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          $key = "${{ secrets.NUGET_API_KEY }}"
          dotnet nuget push "./nupkg/*.nupkg" --api-key $key --source "https://api.nuget.org/v3/index.json"