name: Build and Publish NuGet Package

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Copy README.md to project directory
        run: cp README.md src/AwsTool.Sdk.Sns/

      - name: List files in project directory
        run: ls -la src/AwsTool.Sdk.Sns/
          
      - name: Build the project
        run: dotnet build --configuration Release --no-restore src/AwsTool.Sdk.Sns/AwsTool.Sdk.Sns.csproj

      - name: Pack the project
        run: dotnet pack --configuration Release --no-build --output ./nupkg src/AwsTool.Sdk.Sns/AwsTool.Sdk.Sns.csproj

      - name: Publish NuGet Package
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push "./nupkg/*.nupkg" --api-key $NUGET_API_KEY --source "https://api.nuget.org/v3/index.json"